language: node_js
node_js:
    - node
cache: npm
branches:
    only:
        - master
        - staging
before_install:
    - openssl aes-256-cbc -K $encrypted_78ba3e85acf3_key -iv $encrypted_78ba3e85acf3_iv -in deploy_key.enc -out deploy_key -d
    - chmod 600 ./deploy_key
install:
    - echo "|1|ou/rXNNnoo/7uJCV5N55XXBk1UU=|AgSJZ5fhqLKxtKDYWXEciRNBFLU= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD9383J/S0w5UKl1hy7sSOFAs0uCr75Tt76fRTAYDO/AcwdcmqGuEkuETYCxU2fSxWDuhT6n16q4aMh7asyujtFbBcUX1JFqq5HcimQNXrQUxNAVNHd68IhCWAnmdHPWGl6L14y2UMI/9cfMdP9+j5eT76KCaDnd4QOxBUfNijW61dz/WqlKuREidwo8cLnLdGirTr/LgNXZqQcd3Smpj8/YRT0VP3TP6iClZbUkv9PzrMefYgp5EQuW7nDKEuOssk1644lUKsMIQVsDO5madQVxf+vUFPqg2sy6kU/0eJKQSzLLHLpBe8EzyM1oOqvJCWSE6qC7lO8b4CzGri5xkF" >> $HOME/.ssh/known_hosts
    - npm install
script:
    - npm run build
deploy:
    skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
        all_branches: true
