fragment UserData on User {
    id
    steamID
    username
    displayname
    password
    email
    role
    extraPerm
    jwtEpoch
}

query GET_USER_WITH_ID($id: String!) {
    User(id: $id) {
        ...UserData
    }
}

query GET_USER_WITH_USERNAME($username: String!) {
    allUsers(filter: { username: $username }, first: 1) {
        ...UserData
    }
}

query GET_USER_WITH_EMAIL($email: String!) {
    allUsers(filter: { email: $email }, first: 1) {
        ...UserData
    }
}

query GET_USER_WITH_STEAMID($steamID: String!) {
    allUsers(filter: { steamID: $steamID }, first: 1) {
        ...UserData
    }
}

mutation CREATE_USER_WITH_PASSWORD(
    $username: String!
    $displayname: String!
    $password: String!
    $email: String
    $role: String = "user"
    $jwtEpoch: String!
) {
    createUser(
        input: {
            username: $username
            displayname: $displayname
            password: $password
            email: $email
            role: $role
            extraPerm: []
            jwtEpoch: $jwtEpoch
        }
    ) {
        ...UserData
    }
}

mutation CREATE_USER_WITH_STEAMID(
    $username: String!
    $displayname: String!
    $steamID: String!
    $email: String
    $role: String = "user"
    $jwtEpoch: String!
) {
    createUser(
        input: {
            username: $username
            displayname: $displayname
            steamID: $steamID
            email: $email
            role: $role
            extraPerm: []
            jwtEpoch: $jwtEpoch
        }
    ) {
        ...UserData
    }
}
