query HOME_ALL {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
    favorites {
        title
    }
}

query GET_POSTS {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
}

query GET_FAVORITES {
    favorites {
        title
    }
}

mutation USER_LOGOUT {
    logout
}

mutation USER_LOGIN($username: String!, $password: String!) {
    login(username: $username, password: $password) {
        username
        id
        role
        extraPerm
    }
}
