query HOME_ALL {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
    favorites {
        title
    }
}

query GET_POSTS {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
}

query GET_FAVORITES {
    favorites {
        title
    }
}

mutation USER_LOGOUT {
    logout
}

mutation USER_LOGIN($username: String!, $password: String!) {
    login(input: { username: $username, password: $password }) {
        username
        displayname
        id
        role
        extraPerm
    }
}

mutation USER_REGISTER_WITH_STEAM($username: String!, $email: String) {
    registerWithSteam(input: { username: $username, email: $email }) {
        username
        displayname
        id
        role
        extraPerm
    }
}

mutation USER_REGISTER($username: String!, $password: String!, $confirmPassword: String!, $email: String!) {
    register(input: { username: $username, password: $password, confirmPassword: $confirmPassword, email: $email }) {
        username
        displayname
        id
        role
        extraPerm
    }
}
