query HOME_ALL {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
    favorites {
        title
    }
}

query GET_POSTS {
    posts {
        title
        author {
            firstName
            lastName
        }
    }
}

query GET_FAVORITES {
    favorites {
        title
    }
}

mutation USER_LOGOUT {
    logout
}

mutation USER_LOGIN($username: String!, $password: String!) {
    login(username: $username, password: $password) {
        username
        displayname
        id
        role
        extraPerm
    }
}

mutation USER_REGISTER_WITH_STEAM($username: String!, $email: String) {
    registerWithSteam(username: $username, email: $email) {
        username
        displayname
        id
        role
        extraPerm
    }
}

mutation USER_REGISTER($username: String!, $password: String!, $email: String) {
    register(username: $username, password: $password, email: $email) {
        username
        displayname
        id
        role
        extraPerm
    }
}
